<?php
function footer_code() {
    echo "
    <footer>  
        <section>
            <div id='before-footer-container'>
                <div id='before-footer'>
                    <h2>#VAPE4EVER</h2>
                </div>
                <div id='waves-container'>
                    <svg class='waves behind' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'
                        viewBox='0 24 150 28' preserveAspectRatio='none' shape-rendering='auto'>
                        <defs>
                            <path id='gentle-wave1' d='M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z' />
                        </defs>
                        <g class='parallax'>
                            <use xlink:href='#gentle-wave1' x='48' y='0' fill='rgba(20,45,45, 1)' />
                        </g>
                    </svg>
                    <svg class='waves' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'
                        viewBox='0 24 150 28' preserveAspectRatio='none' shape-rendering='auto'>
                        <defs>
                            <path id='gentle-wave2' d='M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z' />
                        </defs>
                        <g class='parallax'>
                            <use xlink:href='#gentle-wave2' x='48' y='3' fill='rgba(20,45,45, 0.8)' />
                            <use xlink:href='#gentle-wave2' x='48' y='5' fill='rgba(20,45,45,0.6)' />
                            <use xlink:href='#gentle-wave2' x='48' y='7' fill='rgb(20,45,45, 0.4)'/>
                        </g>
                    </svg>
                </div>
            </div>
        </section>
        <div id='footer'>
            <section class='logo'>
                <a href='index.html'>
                    <img src='images/logo/png/logo-no-background.png' alt=''/>
                </a>
            </section>
            <section id='footer-nav'>
                <ul>
                    <li><a href='index.html'>Home</a></li>
                    <li><a href='products.html'>Products</a></li>
                    <li><a href='enquiry.html'>Enquiry</a></li>
                    <li><a href='about.html'>About</a></li>
                    <li><a href='enhancements.html'>Enhancements</a></li>
                </ul>
            </section>
        </div>
    </footer>


    <div class='
    
    '></div>
    ";
}
?>