<?php
    function head_code() {
        echo "
            <head>
                <title>BRUHHH</title>
                <link href='css/style.css' rel='stylesheet'/>
                <link rel='icon' type='image/png' href='images/logo/png/logo.png'/>
                <meta charset='utf-8'/>
                <meta name='author' content='The Chain Smokers'/>
                <meta name='keyword' content='Ass1 html css'/>
                <meta name='description' content='html css'/>
                <meta name='viewport' content='width=device-width, initial-scale=1.0'/>
                <meta name='content-source' content='https://thevapeclub.vn'/>
                <meta name='images-sources' content='internet'/>
                <meta name='presentation-video-link' content='https://www.youtube.com/watch?v=n5zfNCuBe04'/>
            </head>
        ";
    }
?>